# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'python:3.7'

steps:
  - task: CmdLine@2
    inputs:
      script: |
        pip install black
        find . -type f -name "*.py" | xargs black --check --diff



