# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
schedules:
- cron: "0 4 * * *"
  displayName: Daily run
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    pwd
    docker login --username nemaher --password $(pwd)
    docker pull docker.io/nemaher/stocks
    touch ~/Documents/config.yml
    echo key_id = $(alpaca_key_id) >> ~/Documents/config.yml
    echo secret_key = $(alpaca_secret_key) >> ~/Documents/config.yml
    docker run -it -v ~/Documents:config nemaher/stocks trade-stocks --symbol $(symbol)
  displayName: 'Run Docker Image'
