# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
schedules:
- cron: '*/10 14-21 * * 1-5'
  displayName: Daily run
  branches:
    include:
    - master
  always: True

trigger: none 

stages:
- stage: RUN
  displayName: Run image
  jobs:  
  - job: Run
    displayName: Run
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'specific'
        project: '52448eba-e4d0-40b7-949c-c0e84daf42d4'
        pipeline: '2'
        buildVersionToDownload: 'latest'
        downloadType: 'specific'
        itemPattern: '*_model*'
        downloadPath: '$(system.defaultworkingdirectory)'
    - script: |
        tail $(System.ArtifactsDirectory)/$(symbol)_model.h5
        docker login --username nemaher --password $(pwd)
        docker pull docker.io/nemaher/stocks
        mkdir ~/config
        touch ~/config/config.yml
        echo key_id: $(alpaca_key_id) >> ~/config/config.yml
        echo secret_key: $(alpaca_secret_key) >> ~/config/config.yml
        docker run -v ~/config:/config nemaher/stocks trade-stocks --symbol $(symbol) --save-path $(system.defaultworkingdirectory)
        echo '--------------------'
        ls $(system.defaultworkingdirectory)/stocks
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '*'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: '$(symbol)'
        publishLocation: 'Container'

