# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
schedules:
- cron: "0 4 * * *"
  displayName: Daily run
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    docker login --username nemaher --password $(pwd)
    docker pull docker.io/nemaher/stocks
    touch ./alpaca_config.cfg
    echo [alpaca] >> alpaca_config.cfg
    echo key_id = $(alpaca_key_id) >> alpaca_config.cfg
    echo secret_key = $(alpaca_secret_key) >> alpaca_config.cfg
    docker run nemaher/stocks --config ./alpaca_config.cfg trade-stocks --symbol $(symbol)
  displayName: 'Run Docker Image'
