# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    docker pull docker.io/nemaher/stocks
    docker run nemaher/stocks
  displayName: 'Run Docker Image'
