# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# schedules:
# - cron: "0 4 * * *"
#   displayName: Daily run
#   branches:
#     include:
#     - master
stages:
- stage: RUN
  displayName: Run image
  jobs:  
  - job: Run
    displayName: Run
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        docker login --username nemaher --password $(pwd)
        docker pull docker.io/nemaher/stocks
        mkdir ~/config
        touch ~/config/config.yml
        echo key_id = $(alpaca_key_id) >> ~/config/config.yml
        echo secret_key = $(alpaca_secret_key) >> ~/config/config.yml
        docker run -it -v ~/config:config nemaher/stocks trade-stocks --symbol $(symbol)
      displayName: 'Run Docker Image'
