# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
  - cron: '0 16 * * 1-5'  # '*/1 15-22 * * 1-5'
    displayName: Daily run
    branches:
      include:
      - master
    always: True

  #- cron: '30/1 14 * * 1-5'
  #  displayName: Daily run
  #  branches:
  #    include:
  #    - master
  #  always: True

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: '52448eba-e4d0-40b7-949c-c0e84daf42d4'
      pipeline: '2'
      buildVersionToDownload: 'latest'
      downloadType: 'specific'
      downloadPath: '$(system.defaultworkingdirectory)/artifacts'
  - task: CmdLine@2
    displayName: 'Create output dir'
    inputs:
      script: mkdir $(system.defaultworkingdirectory)/output
  - task: Docker@2
    displayName: 'Docker Login'
    inputs:
      containerRegistry: 'dockerHub'
      command: 'login'
      addPipelineData: false
  - task: Docker@2
    displayName: 'Docker Run'
    inputs:
      containerRegistry: 'dockerHub'
      repository: 'nemaher/stocks'
      command: 'run'
      arguments: '-e key_id=$(alpaca_key_id) -e secret_key=$(alpaca_secret_key) -v $(system.defaultworkingdirectory)/artifacts:/artifacts nemaher/stocks trade-stocks'
      addPipelineData: false

  - script: ls $(system.defaultworkingdirectory)/artifacts

